### PR TITLE
Moderncat 0.1 Kit

### PR DESCRIPTION
**Pull request by MessyBookshelf**
A few kicks and Snares, this is my first pull request, if there are any problems let me know.

### CODE REVIEW

**Comment by MessyBookshelf** [comment]
Will resolve the naming issues shortly.

**Comment by MessyBookshelf** [comment]
I'm not too sure about the placement of this folder in the project, since this is a kit I'm working on and will update it could use a separate folder inside the "Drums" directory or should it be it's own directory with sub folders?

**Comment by TheSmallTeaBoi** [comment]
It should be under drums, something like drums/moderncat

**Comment by MessyBookshelf** [comment]
Added some ZYN Presets as well, didn't think it would commit to the same pr.

**Pull request merged**
